"""two streams: care articles, site facts, traffic and crawl

Revision ID: 35b771c92609
Revises: a0d67e5c3b15
Create Date: 2026-08-14 01:09:24.527610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b771c92609'
down_revision: Union[str, Sequence[str], None] = 'a0d67e5c3b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('pillar', sa.String(length=32), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('dek', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('outline', sa.JSON(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('editor_notes', sa.JSON(), nullable=False),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_pillar'), ['pillar'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_run_date'), ['run_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    op.create_table('crawl_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('stream', sa.String(length=8), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('robots_allowed', sa.Boolean(), nullable=False),
    sa.Column('in_sitemap', sa.Boolean(), nullable=False),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('canonical', sa.Text(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('response_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_checks_stream'), ['stream'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_checks_url'), ['url'], unique=False)

    op.create_table('site_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_site_facts_fingerprint')
    )
    with op.batch_alter_table('site_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_facts_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_facts_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('traffic_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('stream', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.Column('bounce_rate', sa.Float(), nullable=False),
    sa.Column('avg_seconds', sa.Float(), nullable=False),
    sa.Column('referrers', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'period_start', 'period_end', name='uq_traffic_window')
    )
    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_stream'), ['stream'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_url'), ['url'], unique=False)

    # Existing rows are all ML-stream, hence the server default on backfill.
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('stream', sa.String(length=8), nullable=False, server_default='ml')
        )
        batch_op.create_index(batch_op.f('ix_candidates_stream'), ['stream'], unique=False)

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('stream', sa.String(length=8), nullable=False, server_default='ml')
        )
        batch_op.create_index(batch_op.f('ix_drafts_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_stream'), ['stream'], unique=False)
        batch_op.create_foreign_key('fk_drafts_article_id', 'articles', ['article_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('stream', sa.String(length=8), nullable=False, server_default='ml')
        )
        batch_op.create_index(batch_op.f('ix_items_stream'), ['stream'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_stream'))
        batch_op.drop_column('stream')

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drafts_article_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_drafts_stream'))
        batch_op.drop_index(batch_op.f('ix_drafts_article_id'))
        batch_op.drop_column('stream')
        batch_op.drop_column('article_id')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_stream'))
        batch_op.drop_column('stream')

    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_url'))
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_stream'))
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_period_start'))
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_period_end'))

    op.drop_table('traffic_snapshots')
    with op.batch_alter_table('site_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_facts_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_site_facts_audience'))

    op.drop_table('site_facts')
    with op.batch_alter_table('crawl_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_checks_url'))
        batch_op.drop_index(batch_op.f('ix_crawl_checks_stream'))

    op.drop_table('crawl_checks')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_run_date'))
        batch_op.drop_index(batch_op.f('ix_articles_pillar'))
        batch_op.drop_index(batch_op.f('ix_articles_audience'))

    op.drop_table('articles')
    # ### end Alembic commands ###
